id: I447D34D5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T14:26:48+00:00'
last_modified: '2022-06-15T17:42:34.000947+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1665
  title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་བསྟན་བཅོས་རྩ་འགྲེལ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ACAA:
      image_group_id: I1KG1842
      title: Volume 1 of theg pa chen po rgyud bla ma'i bstan bcos rtsa 'grel
      total_pages: 354
      order: 1
      base_file: ACAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
